apiVersion: v2
appVersion: 1.53.0
description: A Jaeger Helm chart for Kubernetes
name: jaeger
type: application
version: 3.0.10
# CronJobs require v1.21
kubeVersion: ">= 1.21-0"
keywords:
  - jaeger
  - opentracing
  - tracing
  - instrumentation
home: https://jaegertracing.io
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
sources:
  - https://hub.docker.com/u/jaegertracing/

